name: Java app CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven


      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Build Docker Image
        run: docker-compose down && docker-compose build

      - name: Run Container for Tests
        run: docker-compose up -d

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coworking-spaces-1.0.0-jar
          path: target/*.jar
